### PR TITLE
Port Codebase to Python3

### PR DESCRIPTION
**Pull request by mfonism**
Using `None` as the second argument in a call the `get` method on a Python dictionary is redundant, as this second argument is `None` by default.

The Python Docs for [version 2](https://docs.python.org/2/library/stdtypes.html) and [version 3](https://docs.python.org/3/library/stdtypes.html) have this to say about the `get` method on a `dict`:

```
get(key[, default])

Return the value for key if key is in the dictionary, else default.
If default is not given, it defaults to None, so that this method never raises a KeyError.
```

### CODE REVIEW

**Comment by SteinRobert** [comment]
Hey mate - thank you very much for your contribution. This means we would break Python 2 support, which is basically fine for me since the supports ends anyways.
However, I think it would make sense to clean up the code and remove other Python 2 code snippets (such as `@python_2_unicode_compatible`) as well, wouldn't it?

It would be great if you could incorporate those changes. Do you have the time to do that? Otherwise, it may take a while, I could also update the code in a few weeks.

**Comment by mfonism** [comment]
I would be glad to work on porting the code to Python 3.

I'll start working on it immediately.

**Comment by SteinRobert** [comment]
Great! 🚀 I‘m looking forward to your contribution!

**Comment by mfonism** [comment]
@SteinRobert 

I've ported the codebase to Python3 (at least, to the best of my knowledge 😸).

I've taken out the `future` dependency from the project, and I've rewritten class declarations to do away with old-style/classic classes.

I've also taken out the encoding format declarations, as Python 3 supports writing source code in UTF-8 by default.

I await your feedback.

**Comment by SteinRobert** [comment]
Looks really good! I like it. Thank you very much! I'll release the update on PyPi within the next few days.

**Pull request merged**
